'use server';
/**
 * @fileOverview Professional-grade AI content detection engine.
 *
 * Analyzes text across multiple dimensions including statistical signals
 * (perplexity estimation, burstiness), stylistic markers, vocabulary patterns,
 * structural repetition, and known AI "fingerprints" to produce a reliable,
 * multi-faceted detection report.
 *
 * - detectAI         - Main entry function.
 * - AIDetectionInput  - Input type.
 * - AIDetectionOutput - Output type.
 */

import { z } from 'zod';
import { callGeminiModel } from '../utils';

// ─────────────────────────────────────────────────────────────────────────────
// Schemas
// ─────────────────────────────────────────────────────────────────────────────

export const AIDetectionInputSchema = z.object({
  text: z.string().describe('The input text to analyze for AI generation.'),
  model: z.string().describe('The AI model to use for analysis.'),
});
export type AIDetectionInput = z.infer<typeof AIDetectionInputSchema>;

export const SentenceAnalysisSchema = z.object({
  text: z.string().describe('The sentence text.'),
  score: z
    .number()
    .min(0)
    .max(100)
    .describe('AI probability for this specific sentence (0=Human, 100=AI).'),
  flags: z
    .array(z.string())
    .optional()
    .describe('Specific AI markers detected in this sentence.'),
});

export const WritingPatternSchema = z.object({
  name: z.string().describe('Name of the writing pattern detected.'),
  present: z.boolean().describe('Whether this pattern is present in the text.'),
  description: z.string().describe('What this pattern means for the analysis.'),
});

export const AIDetectionOutputSchema = z.object({
  // ── Core verdict ──────────────────────────────────────────────────────────
  score: z
    .number()
    .min(0)
    .max(100)
    .describe('Overall AI probability score from 0 (Human) to 100 (AI).'),
  isAI: z
    .boolean()
    .describe('True if the overall score is >= 50, indicating likely AI origin.'),
  classification: z
    .enum(['human', 'mixed', 'ai'])
    .describe(
      'Three-way classification: "human" (0-30), "mixed" (31-69), "ai" (70-100).'
    ),
  confidence: z
    .number()
    .min(0)
    .max(100)
    .describe(
      'Confidence level of the verdict (0=very uncertain, 100=highly certain).'
    ),

  // ── Statistical estimates ─────────────────────────────────────────────────
  perplexityScore: z
    .number()
    .min(0)
    .max(100)
    .describe(
      'Estimated text predictability (0=highly unpredictable/human, 100=highly predictable/AI).'
    ),
  burstinessScore: z
    .number()
    .min(0)
    .max(100)
    .describe(
      'Sentence length variation score (0=monotone/AI, 100=highly varied/human).'
    ),
  readabilityScore: z
    .number()
    .min(0)
    .max(100)
    .describe(
      'Flesch-Kincaid style readability estimate (0=very hard, 100=very easy).'
    ),

  // ── Detailed analysis ─────────────────────────────────────────────────────
  aiMarkers: z
    .array(z.string())
    .describe('Specific AI-typical phrases, words, or patterns found in the text.'),
  writingPatterns: z
    .array(WritingPatternSchema)
    .describe('Analysis of key writing pattern signals that differentiate human vs AI text.'),
  sentences: z
    .array(SentenceAnalysisSchema)
    .describe('Per-sentence AI probability breakdown with optional flag annotations.'),

  // ── Summary ───────────────────────────────────────────────────────────────
  summary: z
    .string()
    .describe(
      'A concise, professional explanation of the detection verdict and key reasoning.'
    ),
});
export type AIDetectionOutput = z.infer<typeof AIDetectionOutputSchema>;

// ─────────────────────────────────────────────────────────────────────────────
// Prompt
// ─────────────────────────────────────────────────────────────────────────────

const AI_DETECTION_PROMPT = `You are a world-class AI content forensics expert. Your task is to perform a thorough, multi-dimensional analysis of the provided text and determine with precision whether it was written by a human or generated by an AI language model (such as GPT-4, Claude, Gemini, etc.).

You analyze text the same way a combination of GPTZero, Originality.ai, and Turnitin's AI detector would — using statistical signals, stylistic fingerprints, vocabulary patterns, and structural analysis.

---

## ANALYSIS FRAMEWORK

### 1. STATISTICAL SIGNALS (most reliable indicators)

**Perplexity** — How predictable is each word given the context?
- AI text: LOW perplexity (words are "too expected", sentences follow the most probable path)
- Human text: HIGHER perplexity (more surprising word choices, non-obvious phrasing)
- Score 0-100: 0 = unpredictable/human, 100 = highly predictable/AI

**Burstiness** — How varied are sentence lengths?
- AI text: LOW burstiness (sentences cluster around similar lengths, ~15-25 words each)
- Human text: HIGH burstiness (dramatic swings: 3-word punchy sentences followed by 40-word complex ones)
- Score 0-100: 0 = monotone/AI-like, 100 = highly varied/human-like

**Readability** — Overall reading ease estimate
- Estimate on a 0-100 scale (like Flesch-Kincaid Reading Ease)

### 2. STYLISTIC FINGERPRINTS

Look for these known AI writing patterns (count how many are present):

**AI-Typical Phrases (instant red flags):**
- "It is important to note that..." / "It is worth mentioning..."
- "Furthermore," / "Moreover," / "Additionally," / "Consequently,"
- "It should be noted that..." / "It is crucial to understand..."
- "This demonstrates that..." / "This highlights the importance of..."
- "In conclusion," / "To summarize," / "In summary,"
- "Firstly, ... Secondly, ... Finally, ..."
- "One can see that..." / "We can observe that..."
- "Delve into" / "Shed light on" / "Comprehensive" / "Multifaceted"
- "By leveraging" / "In order to" / "With regard to"
- "Notably," / "Significantly," / "Subsequently,"

**AI-Typical Vocabulary:**
- Overly formal synonyms: "utilize" (use), "endeavor" (try), "facilitate" (help), "ascertain" (find out)
- Abstract buzzwords: "paradigm", "synergy", "holistic", "nuanced", "robust", "pivotal", "paramount"
- Hedging clusters: excessive use of "may", "might", "could", "often", "typically" in quick succession

**AI-Typical Structure:**
- Every paragraph starts with the same syntactic structure
- Perfectly parallel bullet points or numbered lists
- Three-part essay structure (intro → body → conclusion) executed mechanically
- No sentence fragments. No interruptions. No em-dash asides used informally.
- Absence of contractions entirely ("do not" instead of "don't")
- No personal anecdotes, opinions, humor, or emotional text

### 3. HUMAN WRITING SIGNALS

Look for patterns that strongly suggest human authorship:
- Highly irregular sentence lengths (very short AND very long mixed)
- Colloquial expressions, slang, idioms
- Contractions ("don't", "it's", "we're", "can't")
- Personal anecdotes, first-person opinions ("I think", "in my experience")
- Self-corrections or hedging ("or maybe I'm wrong about this")
- Informal transitions ("but", "and", "so", "now", "here's the thing")
- Typos or minor grammatical quirks that were NOT corrected
- Rhetorical questions and direct reader address
- Highly specific, unusual, or niche examples (AI tends to use generic examples)
- Emotional tone: frustration, excitement, humor, sarcasm

### 4. SENTENCE-BY-SENTENCE ANALYSIS

For each individual sentence:
- Estimate AI probability (0=Human, 100=AI)
- Flag specific AI markers found: e.g., "[AI phrase: 'It is important to note']", "[No contractions]", "[Parallel structure]", "[Buzzword: 'comprehensive']", "[Human: colloquial]", "[Human: irregular length]"

### 5. WRITING PATTERNS TO EVALUATE

Assess each of these patterns as present/not present:
1. "Uniform Sentence Length" — sentences all similar length (AI signal)
2. "Absence of Contractions" — no contractions in the text (AI signal)
3. "Formal Transitional Words" — uses furthermore/moreover/additionally (AI signal)
4. "AI Vocabulary Markers" — uses utilize/endeavor/facilitate/paradigm etc. (AI signal)
5. "Mechanical Structure" — rigid intro/body/conclusion without natural deviation (AI signal)
6. "Perplexity Consistency" — word choices are predictably "safe" throughout (AI signal)
7. "No Personal Voice" — no opinions, anecdotes, or first-person perspective (AI signal)
8. "Natural Burstiness" — dramatic variation in sentence length (Human signal)
9. "Colloquial Language" — slang, contractions, informal phrasing (Human signal)
10. "Hedging & Uncertainty" — appropriate self-doubt, not AI overconfidence (Human signal)

---

## SCORING GUIDE

| Score Range | Classification | Meaning |
|-------------|---------------|---------|
| 0-15        | human         | Almost certainly human-written |
| 16-30       | human         | Likely human with minor AI traits |
| 31-50       | mixed         | Possibly AI-assisted or human editing of AI text |
| 51-69       | mixed         | Likely AI with some human editing |
| 70-85       | ai            | Highly likely AI-generated |
| 86-100      | ai            | Almost certainly AI-generated |

**Confidence calibration:**
- High confidence (80-100): Multiple strong signals all point the same direction
- Medium confidence (50-79): Signals are mostly consistent with some ambiguity
- Low confidence (20-49): Mixed signals, text could plausibly go either way
- Very low confidence (0-19): Insufficient evidence or highly ambiguous text

---

## TEXT TO ANALYZE:

"""
{{text}}
"""

---

## CRITICAL OUTPUT INSTRUCTIONS:

You MUST return a JSON object with EXACTLY these keys (no extras, no missing keys):

{
  "score": <integer 0-100, overall AI probability>,
  "isAI": <boolean, true if score >= 50>,
  "classification": <"human" | "mixed" | "ai">,
  "confidence": <integer 0-100>,
  "perplexityScore": <integer 0-100>,
  "burstinessScore": <integer 0-100>,
  "readabilityScore": <integer 0-100>,
  "aiMarkers": <array of strings listing specific AI markers found>,
  "writingPatterns": <array of objects: { "name": string, "present": boolean, "description": string }>,
  "sentences": <array of objects: { "text": string, "score": integer 0-100, "flags": array of strings }>,
  "summary": <string, 2-4 sentence professional verdict>
}

Rules:
- "score" MUST be an integer (not float). Round to nearest integer.
- "isAI" MUST be exactly (score >= 50).
- "classification" MUST match: score 0-30 = "human", 31-69 = "mixed", 70-100 = "ai".
- "aiMarkers" MUST be an array. If none found, use an empty array [].
- "writingPatterns" MUST contain all 10 patterns listed above.
- "sentences" MUST cover every sentence in the text (do not skip any).
- All scores (score, confidence, perplexityScore, burstinessScore, readabilityScore, per-sentence score) MUST be integers between 0 and 100 inclusive.
- Do NOT use markdown formatting inside the JSON values.
- Do NOT add text before or after the JSON.`;

// ─────────────────────────────────────────────────────────────────────────────
// Post-processing: normalize, clamp, validate derived fields
// ─────────────────────────────────────────────────────────────────────────────

function clamp(value: number, min = 0, max = 100): number {
  return Math.round(Math.min(max, Math.max(min, value)));
}

function deriveClassification(score: number): 'human' | 'mixed' | 'ai' {
  if (score <= 30) return 'human';
  if (score <= 69) return 'mixed';
  return 'ai';
}

function normalizeOutput(raw: AIDetectionOutput): AIDetectionOutput {
  const score = clamp(raw.score);
  const isAI = score >= 50;
  const classification = deriveClassification(score);

  return {
    ...raw,
    score,
    isAI,
    classification,
    confidence: clamp(raw.confidence),
    perplexityScore: clamp(raw.perplexityScore),
    burstinessScore: clamp(raw.burstinessScore),
    readabilityScore: clamp(raw.readabilityScore),

    // Ensure aiMarkers is always an array
    aiMarkers: Array.isArray(raw.aiMarkers) ? raw.aiMarkers : [],

    // Normalize writingPatterns
    writingPatterns: Array.isArray(raw.writingPatterns)
      ? raw.writingPatterns.map((p) => ({
        name: p.name ?? 'Unknown Pattern',
        present: Boolean(p.present),
        description: p.description ?? '',
      }))
      : [],

    // Normalize per-sentence scores
    sentences: Array.isArray(raw.sentences)
      ? raw.sentences.map((s) => ({
        text: s.text ?? '',
        score: clamp(s.score),
        flags: Array.isArray(s.flags) ? s.flags : [],
      }))
      : [],

    summary: raw.summary ?? 'Analysis complete.',
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────────────────────────────────────

export async function detectAI(input: AIDetectionInput): Promise<AIDetectionOutput> {
  const output = await callGeminiModel({
    model: input.model,
    prompt: AI_DETECTION_PROMPT,
    input: input,
    outputSchema: AIDetectionOutputSchema,
    config: {
      temperature: 0.1,
      topP: 0.9,
    },
  });

  return normalizeOutput(output);
}

