
/**
 * @fileOverview Allows the user to select from multiple AI models.
 *
 * @exports selectAIModel
 * @exports SelectAIModelInput
 * @exports SelectAIModelOutput
 */

import { z } from 'zod';
import { callGeminiModel } from '../utils';

export const SelectAIModelInputSchema = z.object({
  modelName: z.string().describe('The name of the AI model identifier to use (e.g. gemini-3-flash).'),
  sentence: z.string().describe('The sentence to be expanded.'),
  maxWords: z.number().describe('The maximum number of words in the expanded sentence.'),
  tone: z.string().describe('The tone of voice for the expansion (e.g., Formal, Casual).'),
});
export type SelectAIModelInput = z.infer<typeof SelectAIModelInputSchema>;

export const SelectAIModelOutputSchema = z.object({
  expandedSentence: z.string().describe('The expanded sentence generated by the selected AI model.'),
});
export type SelectAIModelOutput = z.infer<typeof SelectAIModelOutputSchema>;

const SELECT_MODEL_PROMPT = `You are an AI assistant that expands sentences.

Expand the following sentence to a maximum of {{maxWords}} words using a {{tone}} tone.

Sentence: {{sentence}}

Provide your response as a JSON object with a single key "expandedSentence".`;

export async function selectAIModel(input: SelectAIModelInput): Promise<SelectAIModelOutput> {
  return await callGeminiModel({
    model: input.modelName,
    prompt: SELECT_MODEL_PROMPT,
    input: input,
    outputSchema: SelectAIModelOutputSchema,
  });
}

