
'use server';

/**
 * @fileOverview Allows the user to select from multiple AI models to use for sentence expansion.
 *
 * @exports selectAIModel
 * @exports SelectAIModelInput
 * @exports SelectAIModelOutput
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SelectAIModelInputSchema = z.object({
  modelName: z.string().describe('The name of the AI model to use for sentence expansion.'),
  sentence: z.string().describe('The sentence to be expanded.'),
  maxWords: z.number().describe('The maximum number of words in the expanded sentence.'),
  tone: z.string().describe('The tone of voice for the expansion (e.g., Formal, Casual).'),
});
export type SelectAIModelInput = z.infer<typeof SelectAIModelInputSchema>;

const SelectAIModelOutputSchema = z.object({
  expandedSentence: z.string().describe('The expanded sentence generated by the selected AI model.'),
});
export type SelectAIModelOutput = z.infer<typeof SelectAIModelOutputSchema>;

export async function selectAIModel(input: SelectAIModelInput): Promise<SelectAIModelOutput> {
  return selectAIModelFlow(input);
}

const prompt = ai.definePrompt({
  name: 'selectAIModelPrompt',
  input: {schema: SelectAIModelInputSchema},
  output: {schema: SelectAIModelOutputSchema},
  prompt: `You are an AI assistant that expands sentences using the specified AI model.

  Expand the following sentence to a maximum of {{maxWords}} words using the {{modelName}} model, with a {{tone}} tone.

  Sentence: {{{sentence}}}
  
  Provide your response as a JSON object with a single key "expandedSentence".`,
});

const selectAIModelFlow = ai.defineFlow(
  {
    name: 'selectAIModelFlow',
    inputSchema: SelectAIModelInputSchema,
    outputSchema: SelectAIModelOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
